title: Dymka
email: info@dymka.org
description: Dymka is an independent software studio specializing in native mobile applications and interactive games.
url: 'https://www.dymka.org'

# Jekyll Build Settings
markdown: kramdown
theme: null

# Exclude list
exclude:
  - README.md
  - .prettierrc
  - .htmlhintrc
  - package.json
  - package-lock.json
  - scripts
  - node_modules
  - src
